### ISSUE TITLE
Histolab dependency conflict

### ISSUE THREAD

**Issue by alessiamarcolini** [TIO-IKIM/PathoPatcher#3]
Hi, one of the histolab maintainers here 👋 

I saw that you had to remove histolab as a dependency due to conflicts. Could you share here what is the cause of the conflict or open an issue directly at https://github.com/histolab/histolab/issues?

We are planning the next chunk of work and we could include this as well :)

Best,
Alessia

**Comment by FabianHoerst** [comment]
Hi, I think the issue has been fixed. In generel your dependencies are very restrictive, therefore I just removed it for a quick fix and to keep the dependency clean. However, I will most likely integrate your new version 0.7 into my project again.

**Comment by alessiamarcolini** [comment]
Hi @FabianHoerst, thank you for coming back to me. Could you let me know which dependencies gave you trouble or which ones you think are too restrictive? Thanks.

**Comment by FabianHoerst** [comment]
Hi, the problem was that I experimented with a newer openslide, numpy and PIL version, which lead to dependency conflicts during development. I am very sorry that I cannot reproduce the behaviour again, as I have no logs stored with the histolab 0.6.0 version
